name: Playwright Prod Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

jobs:
  run-prod-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [US_Prod_Desktop, US_Prod_Mobile, CA_Prod_Desktop, CA_Prod_Mobile]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests for Prod (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }}

      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4  # ✅ Fixed the deprecated version
        with:
          name: playwright-prod-results
          path: playwright-report/
