name: Playwright Tests - Prod

on:
  push:
    branches:
      - main  # Runs when you push to 'main' (or 'prod') branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests (Prod)
        run: npx playwright test --config=playwright.config.ts --reporter=html,json

      - name: Upload Playwright Test Results (Artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-prod
          path: test-report/
          retention-days: 11
