name: Playwright Prod Tests

on:
  workflow_dispatch: # Manually trigger workflow
  push:
    branches:
      - main # Runs only on the 'main' branch
  schedule:
    - cron: "0 3 * * *" # Runs every day at 3 AM UTC

jobs:
  run-prod-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [US_Prod_Desktop, US_Prod_Mobile, CA_Prod_Desktop, CA_Prod_Mobile]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests for Prod (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }}

      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-prod-results
          path: playwright-report/
