name: Spanx Prod Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *" # Runs daily at 03:00 UTC

jobs:
  run-prod-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [US_Prod_Desktop, US_Prod_Mobile, CA_Prod_Desktop, CA_Prod_Mobile]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Setup Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests for Prod (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }}

      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4  
        with:
          name: playwright-prod-results-${{ matrix.project }}
          path: playwright-report/

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 587  # Use 465 for SSL, 587 for TLS
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Spanx Production Automation Script Execution Report - Prod (${{ matrix.project }})"
          body: "Spanx Production Automation Script Execution has completed. Please find the attached report."
          to: "sathiksha.sb@gmail.com"
          from: "Playwright Automation <${{ secrets.SMTP_USERNAME }}>"
          attachments: playwright-report/index.html
