name: Playwright Dev Tests

on:
  workflow_dispatch: # Manually trigger workflow
  push:
    branches:
      - dev # Runs only on the 'dev' branch
  pull_request:
    branches:
      - dev

jobs:
  run-dev-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [US_Dev_Desktop, US_Dev_Mobile, CA_Dev_Desktop, CA_Dev_Mobile]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Playwright Tests for Dev (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }}

      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-dev-results
          path: playwright-report/
