name: Spanx Prod Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

jobs:

  run-prod-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [US_Prod_Desktop, US_Prod_Mobile, CA_Prod_Desktop, CA_Prod_Mobile]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests for Prod (${{ matrix.project }})
        run: npx playwright test --project=${{ matrix.project }}

      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
       
          name: ${{ matrix.project }}
          path: playwright-report/

  send-emails:
    needs: run-prod-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download US_Prod_Desktop
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: US_Prod_Desktop
          path: us/desktop

      - name: Download US_Prod_Mobile
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: US_Prod_Mobile
          path: us/mobile

      - name: Zip US Reports
        run: zip -r us_prod_reports.zip us/

      - name: Send US Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Spanx Production Automation Script Execution Report - Prod (US)"
          body: "Spanx Production Automation Script Execution for US has completed. Please find the attached consolidated report."
          to: "sathiksha.sb@gmail.com"
          from: "Playwright Automation <${{ secrets.SMTP_USERNAME }}>"
          attachments: us_prod_reports.zip

      - name: Download CA_Prod_Desktop
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: CA_Prod_Desktop
          path: ca/desktop

      - name: Download CA_Prod_Mobile
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: CA_Prod_Mobile
          path: ca/mobile

      - name: Zip CA Reports
        run: zip -r ca_prod_reports.zip ca/

      - name: Send CA Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Spanx Production Automation Script Execution Report - Prod (CA)"
          body: "Spanx Production Automation Script Execution for CA has completed. Please find the attached consolidated report."
          to: "sathiksha.sb@gmail.com"
          from: "Playwright Automation <${{ secrets.SMTP_USERNAME }}>"
          attachments: ca_prod_reports.zip
